### ISSUE TITLE
Use non-atomic operations for ST counters

### ISSUE THREAD

**Issue by noughtmare** [sergv/atomic-counter#2]
The use of atomic operations slows down the ST counters significantly.

For example take this code:

```haskell
programCnt :: Cnt.Counter s -> ST s ()
programCnt cnt = do
  n <- Cnt.get cnt
  if n <= 0
     then pure ()
     else do
       Cnt.set cnt $! n - 1
       programCnt cnt

countdownCnt :: Int -> Int
countdownCnt n = runST $ do
  cnt <- Cnt.new n
  programCnt cnt
  Cnt.get cnt 

main = putStrLn . show $ countdownCnt 100000000
```

The timing is:

```
Total   time    1.341s  (  1.350s elapsed)
```

Compare that with:

```haskell
programST :: STRef s Integer -> ST s ()
programST ref = do
  n <- readSTRef ref
  if n <= 0
    then pure ()
    else do
      writeSTRef ref $! n - 1
      programST ref

countdownST :: Integer -> Integer
countdownST n = runST $ do
  ref <- newSTRef n
  programST ref
  s <- readSTRef ref
  pure s

main :: IO ()
main = putStrLn . show $ countdownST 100000000
```

Which takes only this long:

```
Total   time    0.311s  (  0.320s elapsed)
```

**Comment by noughtmare** [comment]
Actually, it can go wrong if you use [`stToIO`](https://hackage.haskell.org/package/base-4.17.0.0/docs/Control-Monad-ST.html#v:stToIO):

```haskell
import Control.Monad.ST
import Control.Monad.ST.Unsafe
import Control.Concurrent
import Data.STRef

programST :: STRef s Integer -> ST s ()
programST ref = do
  n <- readSTRef ref
  if n <= 0
    then pure ()
    else do
      unsafeIOToST yield
      writeSTRef ref $! n - 1
      programST ref

countdownST :: Integer -> IO Integer
countdownST n = do
  ref <- stToIO (newSTRef n)
  forkIO $ stToIO (programST ref)
  stToIO (programST ref)
  s <- stToIO (readSTRef ref)
  pure s

main :: IO ()
main = do
  putStrLn . show =<< countdownST 1000000
```

(The `unsafeIOToST yield` is only to make it more likely that weird concurrent interleavings occur)

Compiling with `ghc -O2 T.hs -threaded` and running with `./T +RTS -N2` sometimes gives me unexpected results:

```
$ ./T +RTS -N2
129

$ ./T +RTS -N2
100
```

Although, I have no idea why the numbers are positive. I would have certainly expected negative numbers.

**Comment by sergv** [comment]
> The use of atomic operations slows down the ST counters significantly.

Regarding atomicity - I like to think taht point of this package is to atomic operations. In other words the operations are either atomic or they're not provided. As a nice bonus the operations are pretty fast compared to IORef, most likely due to unboxed nature of counters.

For the `ST` monad one can argue that each `ST` execution will necessarily happen in the same haskell thread of execution but it's definitely possible to try to overcome that and unsafely coerce `ST` to run across multiple threads and this package aims to do atomic operations ever in that case.

> For example take this code:

I'm struggling to reproduce your numbers. Could you please run my benchmark below and share what you get?

```haskell
#!/usr/bin/env cabal
{- cabal:
build-depends:
  , atomic-counter
  , base
  , tasty-bench
-}

{-# LANGUAGE BangPatterns        #-}
{-# LANGUAGE ImportQualifiedPost #-}

module Main (main) where

import Control.Concurrent.Counter.Lifted.ST qualified as Cnt
import Control.Monad.ST
import GHC.STRef

import Test.Tasty.Bench

programCnt' :: Cnt.Counter s -> ST s ()
programCnt' cnt = go
  where
    go = do
      old <- Cnt.sub cnt 1
      if old <= 0
      then pure ()
      else go

countdownCnt' :: Int -> Int
countdownCnt' n = runST $ do
  cnt <- Cnt.new n
  programCnt' cnt
  Cnt.get cnt

programCnt :: Cnt.Counter s -> ST s ()
programCnt cnt = do
  n <- Cnt.get cnt
  if n <= 0
     then pure ()
     else do
       Cnt.set cnt $! n - 1
       programCnt cnt

countdownCnt :: Int -> Int
countdownCnt n = runST $ do
  cnt <- Cnt.new n
  programCnt cnt
  Cnt.get cnt

programST :: STRef s Int -> ST s ()
programST ref = do
  n <- readSTRef ref
  if n <= 0
    then pure ()
    else do
      writeSTRef ref $! n - 1
      programST ref

countdownST :: Int -> Int
countdownST n = runST $ do
  ref <- newSTRef n
  programST ref
  s <- readSTRef ref
  pure s

main :: IO ()
main = do
  let n :: Int
      !n = 100000000
  defaultMain
    [ bench "ST" $ nf countdownST n
    , bench "Counter" $ nf countdownCnt n
    , bench "Counter'" $ nf countdownCnt' n
    ]
```

Here's what I'm getting:
```
$ ./Main.hs
All
  ST:       OK (6.63s)
    2.204 s ±  92 ms
  Counter:  OK (3.93s)
    1.970 s ±  31 ms
  Counter': OK (2.12s)
    706  ms ± 7.9 ms

All 3 tests passed (14.66s)
```

For comparison, I added a third version of the problem you proposed that uses the [sub](https://hackage.haskell.org/package/atomic-counter-0.1/docs/Control-Concurrent-Counter-Lifted-ST.html#v:sub) function to decrement the counter. It seems to be faster than `STRef`s on my setup, I'm curious how it would do on yours.

Use of `get` and `set` is fine but the primary use case I envisioned for this package is to use the rest of the functions, like `add`, to do atomic updates from different threads of the same counter.

> Actually, it can go wrong if you use [stToIO](https://hackage.haskell.org/package/base-4.17.0.0/docs/Control-Monad-ST.html#v:stToIO):

I'm not sure what you mean by wrong here. You probably meant to run atomic counters with `stToIO` but your example uses STRefs which are not atomic and can explain some other puzzling behaviour you observed.

> Although, I have no idea why the numbers are positive. I would have certainly expected negative numbers.

Numbers are positive because your update functions stop subtractions once the counter reaches 0 and counters starts with a positive value of 1000000.

It's interesting that you sometimes get non-zero result whereas I seem to always (having tried less than 10 times though) get 0 in the end. However I think that's explainable too: you start thread with `forkIO` but you never wait for it to finish. Scheduler can make it so that when `stToIO (programST ref)` in main thread finishes the forked thread is woken up and gets to do some work, then it gets put to sleep and the main thread gets to read intermeadiate value of the counter.

**Comment by noughtmare** [comment]
I'm getting these times:

```
All
  ST:       OK (1.89s)
    270  ms ±  20 ms
  Counter:  OK (3.32s)
    1.660 s ±  28 ms
  Counter': OK (2.90s)
    966  ms ±  28 ms
```

I should have mentioned that GHC 9.4.4 has a bug which causes the ST implementation to significantly underperform: https://gitlab.haskell.org/ghc/ghc/-/issues/22764, so I used 9.4.3 to compile this benchmark.

**Comment by noughtmare** [comment]
RE: the possibility of unsafely coercing, fair enough, this package is called `atomic-counter` after all. Maybe a note in the documentation about non-atomic `STRef` probably being faster could be useful (if you can also reproduce my 9.4.3 timings).

I didn't think of using `sub` in that way. Using the `get` and `set` operations is not essential to me. That was just the first thing that I could think of.

> I'm not sure what you mean by wrong here.

I meant that my suggestion of using non-atomic operations in ST can go wrong even with "safe" functions like `stToIO`.

> Numbers are positive because your update functions stop subtractions once the counter reaches 0 and counters starts with a positive value of 1000000. 

Note that the `programST` function doesn't reset the counter to 1000000, so it can't just be that the main thread finishes before the forked thread.

What I think might be happening is that at some point the forked thread reads the value, then the main thread does 100 iterations reaching the end but staying before the last read, then the forked thread writes the old number `100`, and only then does the main thread read the final value.

Maybe you're never getting nonzero also because of that same bug in 9.4.4? The bug is that the compiler adds an extra fence, so that could prevent the race condition.

**Comment by sergv** [comment]
Thanks for bringing this up and for providing link to the relevant GHC issue. I was not paying much attention to how GHC made IORefs work better in the concurrent setting.

I managed to reproduce your numbers with `9.4.3`. It seems some fixes are still in the queue for https://gitlab.haskell.org/ghc/ghc/-/issues/22764 so it's interesting to see how future GHC will perform.

I extended readme with results of single-threaded comparison and a suggestion to not expect much from this package in a single-threaded setting.
