### ISSUE TITLE
Could this package be merged with atomic-primops?

### ISSUE THREAD

**Issue by mitchellwrosen** [sergv/atomic-counter#7]
Hey! I just thought I'd float the idea of merging this package with `atomic-primops`, which also exposes a similar counter type.

It seems this package has a default cmm implementation, whereas `atomic-primops` does not. Perhaps that code could be contributed to `atomic-primops` as well?

Having two atomic counter packages is of course not the end of the world, but it would be (slightly) better for ecosystem discoverability and cohesion to have just one.

**Comment by sergv** [comment]
The point of `atomic-counter` is pretty silly: I wanted an atomic counter myself, tried to search for it on the Internet/Hackage and failed miserably. Stated simply, the idea is discoverability so that obvious search term will lead one to the package that does it. Maybe I'm just bad at searching on the Internet.

On a different note, some, perhaps questionable, design decisions were made in this package that will likely not feel at home in `atomic-primops`: the distinction between API in `IO`, `ST` and a raw one on Unlifted kind for guaranteed absence of any overheads. I can totally see why someone would not want to provide all 3 in their package, but I at least did use the Unlifted-kind-based one myself.

If anyone wants to contribute cmm to `atomic-primops` I'm all for it. Although this whole thing is a bit experimental overall (i.e. could potentially be retracted, altough the results so far confirm that it works OK so most likely wouldn't).

**Comment by sergv** [comment]
I'm cleaning up stale issues, please reopen if you feel it's still relevant.
